### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by tallywiesenberg** [tellor-io/disputable-values-monitor#86]
build `AutoDisputerConfig` class inheriting `ConfigOptions`
- includes...
    - freshness (global, in seconds)
    - list of monitored query types w/ threshold type and threshold amount for each

Ex:
```yaml
# AutoDisputer configuration file
disputer:
  freshness: 86400 # in seconds
  feeds: # please reference https://github.com/tellor-io/dataSpecs/tree/main/types for examples of QueryTypes w/ Query Parameters
    SpotPrice:
      asset: eth
      currency: usd
      threshold:
        type: percentage
        amount: 50 # 50%
```
Test:

- [ ] Assert all attributes read correctly
- [ ] Assert writing to class correctly
- [ ] Assert writing to file correctly
